routes/web.php
<?php

use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\ChefController;
use App\Http\Controllers\Dashboard\CompanyController;
use App\Http\Controllers\Dashboard\ComponentController;
use App\Http\Controllers\Dashboard\DelegateController;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\InvoiceController;
use App\Http\Controllers\Dashboard\ItemController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ProductController;
use App\Http\Controllers\Dashboard\StockController;
use App\Http\Controllers\Dashboard\SupplierController;
use App\Http\Controllers\Dashboard\UnitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::group(['namespace' => 'Dashboard'], function () {

//Route::view('main','dashboard.Units.index');
    Route::get('login',[HomeController::class,'viewLogin'])->name('login');
    Route::post('login',[HomeController::class,'login'])->name('dashboard.saveLogin');

    Route::group(['middleware' => 'auth'], function () {

        Route::get('/index', [HomeController::class,'home'])->name('index');
        Route::get('showProfile',   [HomeController::class,'showProfile'])->name('show_profile');
        Route::post('updateProfile/{admin}',  [HomeController::class,'UpdateProfile'])->name('update_profile');
        Route::post('logout',[HomeController::class,'logout'])->name('dashboard.logout');


        Route::resource('units',UnitController::class);
        Route::resource('companies',CompanyController::class);
        Route::resource('categories',CategoryController::class);
        Route::resource('items',ItemController::class);
        Route::resource('suppliers',SupplierController::class);
        Route::resource('delegates',DelegateController::class);

        Route::resource('invoices',InvoiceController::class);
        Route::get('invoices/item/{id}', [InvoiceController::class ,'item'])->name('unit');
        Route::get('invoices/delegate/{id}', [InvoiceController::class ,'delegate'])->name('supplier.delegates');


        Route::get('stocks',[StockController::class,'index'])->name('stocks.index');

        Route::resource('products',ProductController::class);
        Route::get('/item/{id}', [InvoiceController::class ,'item'])->name('item.unit');
        Route::get('product',[ProductController::class,'createDeteils'])->name('product.create');
        Route::post('product',[ProductController::class,'storeDeteils'])->name('product.store');

        Route::resource('components',ComponentController::class);

        Route::resource('chefs',ChefController::class);
        Route::resource('orders',OrderController::class);
        Route::get('orders/product/{id}',[OrderController::class,'product']);
//        Route::get('orders',[OrderController::class,'orderRequest']);

//        Route::view('Card/title','dashboard.Orders.order-request');

        //        Route::group(['middleware' => 'CheckPerm'], function () {});
    });
//});

app/Models/Delegate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Delegate extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function supplier(){
        return $this->belongsTo(Supplier::class);
    }

    public function setVisitingAttribute($value)
    {
        $this->attributes['visiting'] = json_encode($value);
    }

    public function getVisitingAttribute($value)
    {
//        return  json_decode($this->visiting);
        return $this->attributes['visiting'] = json_decode($value);
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/AdminGroupController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminGroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::latest()->get();
        return view('dashboard.Categories.index',compact('categories'));
    }

   
    public function create()
    {
        return view('dashboard.Categories.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required|string|unique:categories',
            'notes' => 'nullable|string',
        ],
            [
                'name.required'=>'اسم القسم مطلوب',
                'name.string'=>'يجب ان يكون اسم القسم كلمه',
                'name.unique'=>'اسم القسم موجود من قبل',
                'notes.string'=>'يجب ان يكون ملاحظه القسم كلمات',
            ]);

        Category::create([
            'name'=>$request->name,
            'notes'=>$request->notes,
        ]);
        return redirect()->route('categories.index')->with('message', 'تم إضافه القسم بنجاح');

    }

    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $category = Category::whereId($id)->first();
        if ($category){
            return view('dashboard.Categories.edit',compact('category'));
        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }

   
    public function update(CategoryRequest $request, $id)
    {
        $category = Category::whereId($id)->first();
        if ($category){
            $category->update($request->validated());
            return redirect()->route('categories.index')->with('message', 'تم تعديل القسم بنجاح');

        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }
    
    public function destroy($id)
    {
        $category = Category::whereId($id)->first();
        if ($category){
            $category->delete();
            return redirect()->route('categories.index')->with('message', 'تم حذف القسم بنجاح');
        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }
}

app/Http/Controllers/Dashboard/ChefController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ChefRequest;
use App\Models\Chef;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Exception ;

class ChefController extends Controller
{
    public function index()
    {
       $chefs = Chef::latest()->get();
       return view('dashboard.Chefs.index', compact('chefs'));
    }


    public function create()
    {
        return view('dashboard.Chefs.create');
    }

    public function store(ChefRequest $request)
    {
        try{
            $request->except(['image']);
            $image ='';
            if ($request->image) $image =  uploaded($request->image, 'chef');
            $chef = Chef::create($request->validated());
            $chef->update([
                'image' =>$image,
            ]);
            $chef->save();
            return redirect()->route('chefs.index')->with('success', 'تم اضافه الشيف بنجاح');

        }
        catch (\Exception $er){
//            return $er;
            return redirect()->route('chefs.index')->with('error', 'حدث خطأ يرجي المحاوله مره اخري');
        }

    }




    public function show($id)
    {
        $chef = Chef::find($id);
        if (!$chef) {
            return redirect()->route('chefs.index')->with('error', 'لا يوجد شيف بهذه البيانات' );
        }
        return view('dashboard.Chefs.show', compact('chef'));

    }


    public function edit($id)
    {
        try{
            $chef = Chef::find($id);
            if (!$chef) {
                return redirect()->route('chefs.index')->with('error','لا يوجد شيف بهذه البيانات');
            }

            return view('dashboard.Chefs.edit', compact('chef'));
        }
        catch (\Exception $ex){

            return redirect()->route('chefs.index')->with('error', 'حدث خطأ يرجي المحاوله مره اخري');
        }

    }


    public function update(ChefRequest $request, $id)
    {
        try{
            $chef = Chef::find($id);
            $request_data = $request->except(['password','image']);


            if ($request->has('password')){
                $request_data['password'] = $request->password;
            }

            if ($request->has('image'))
            {
                File::delete(public_path('uploads/chefs/' . $chef->image));

                $request_data['image'] = uploaded($request->image, 'chef');
            }
            $chef->update($request_data);
            return redirect()->route('chefs.index')->with('message', 'تم التعديل  بنجاح');
        }

        catch (\Exception $ex){
            return redirect()->route('chefs.index')->with('error', 'حدث خطأ يرجي المحاوله مره اخري');
        }
    }


    public function destroy($id)
    {
        $chef = Chef::find($id);

        if(!$chef) return back()->with('error', 'لا يوجد بيانات');
        try
        {
            File::delete(public_path('uploads/chefs/' . $chef->image));
            $chef->delete();
            return redirect()->route('chefs.index')->with('message', 'تم حذف الشيف بنجاح');
            }
        catch (Exception $e) {
            return back()->with('error', 'لا يوجد بيانات');

        }

    }
}

app/Http/Controllers/Dashboard/CompanyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    public function index()
    {
        $companies = Company::latest()->get();
        return view('dashboard.Companies.index',compact('companies'));
    }


    public function create()
    {
        return view('dashboard.Companies.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required|string|unique:companies',
            'notes' => 'nullable|string',
        ],
            [
                'name.required'=>'اسم الشركه مطلوب',
                'name.string'=>'يجب ان يكون اسم الشركه كلمه',
                'name.unique'=>'اسم الشركه موجود من قبل',
                'notes.string'=>'يجب ان يكون ملاحظه الشركه كلمات',
            ]);

        Company::create([
            'name'=>$request->name,
            'notes'=>$request->notes,
        ]);
        return redirect()->route('companies.index')->with('message', 'تم إضافه الشركه بنجاح');

    }

    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $company = Company::whereId($id)->first();
        if ($company){
            return view('dashboard.Companies.edit',compact('company'));
        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }

    public function update(CompanyRequest $request, $id)
    {
        $company = Company::whereId($id)->first();
        if ($company){
            $company->update($request->validated());
            return redirect()->route('companies.index')->with('message', 'تم تعديل الشركه بنجاح');

        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }

    public function destroy($id)
    {
        $company = Company::whereId($id)->first();
        if ($company){
            $company->delete();
            return redirect()->route('companies.index')->with('message', 'تم حذف الشركه بنجاح');
        }else{
            return back()->with('error', 'لا يوجد بيانات');

        }
    }
}

app/Http/Controllers/Dashboard/ComponentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ComponentRequest;
use App\Models\Component;
use App\Models\Item;
use App\Models\Product;
use Illuminate\Http\Request;

class ComponentController extends Controller
{

    public function index()
    {
        $components = Component::latest()->get();
        return view('dashboard.Components.index',compact('components'));

    }

    public function create()
    {
        $products = Product::get();
        $items = Item::get();
        return view('dashboard.Components.create',compact('products','items'));

    }


    public function store(ComponentRequest $request)
    {
        try{
            $product = Product::where('id',$request->product_id)->first();
       // update cost_price Product
            Component::create($request->validated()+[
//                'size_one_gram' => ,
                ]);
            return redirect()->route('components.index')->with('message', 'تم إضافه المكون بنجاح');

        }catch (\Exception $e){
            return back()->with('error', 'حدث خطأ في إرسال البيانات');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/StockController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Stock;
use Illuminate\Http\Request;

class StockController extends Controller
{
    public function index(){
        $stocks = Stock::latest()->get();
        return view('dashboard.Stocks.index',compact('stocks'));
    }
}

resources/views/dashboard/Delegates/index.blade.php
@extends('dashboard.layouts.master')

@section('title', 'المندوبين')


@section('content')
    <div class="content-wrapper container-xxl p-0">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-start mb-0">إداره المخابز</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('index')}}">الرئسيه</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{route('delegates.index')}}">المندوبين</a>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
                    <div class="mb-1 breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle waves-effect waves-float waves-light" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="app-todo.html"><i class="me-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="me-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="me-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="me-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="content-body"><!-- Ajax Sourced Server-side -->
            <section id="responsive-datatable">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @include('dashboard.includes.errors')
                            <div class="card-header border-bottom">
                                <a href="{{route('delegates.create')}}" class="create-new btn btn-primary"><span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus me-50 font-small-4"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>إضافه مندوب جديد</span></a>
                                {{--<h4 class="card-title">Responsive Datatable</h4>--}}
                            </div>
                            <div class="card-datatable">
                                <table class="dt-responsive table">
                                    <thead>
                                        <tr>
                                    <th></th>
                                    <th>#</th>
                                    <th>الاسم</th>
                                    <th>رقم الهاتف</th>
                                    <th>التاجر</th>
                                    <th>مواعيد الزياره</th>
                                    <th>ملاحظه</th>
                                    <th>خيارات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse($delegates as $delegate)
                                        <tr>
                                    <td></td>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$delegate->name}}</td>
                                    <td>{{$delegate->phone}}</td>
                                    <td>{{$delegate->supplier->name}}</td>
                                   <td>
                                       {{--{{json_decode($delegate->visiting_dates)}}--}}
                                       {{--@php--}}
                                           {{--$delegateVisiting = json_decode($delegate->visiting_dates, true);--}}
                                     {{--// dd($delegateVisiting);--}}
                                       {{--@endphp--}}
                                       {{--@dd(count($delegateVisiting))--}}
                                       {{--@foreach($delegateVisiting as $key => $value)--}}
                                           {{--{{$value}},--}}
                                       {{--@endforeach--}}

                                       @foreach((array)($delegate->visiting) as $value)
                                            {{$value}},
                                       @endforeach

                                   </td>
                                    {{--<td>{{$delegate->visiting_dates}}</td>--}}
                                    <td>{{$delegate->notes}}</td>
                                    <td>
                                    <div class="dropdown">
                                    <button type="button" class="btn btn-sm dropdown-toggle hide-arrow py-0 waves-effect waves-float waves-light" data-bs-toggle="dropdown">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-end">
                                    <a class="dropdown-item" href="{{route('delegates.edit',$delegate->id)}}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 me-50"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                    <span>تعديل</span>
                                    </a>
                                        <form method="POST" action="{{ route('delegates.destroy', $delegate->id) }}">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                             <button type="submit" class="dropdown-item delete-action btn-danger show_confirm"  data-id="{{$delegate->id}}">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash me-50"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                                             <span>حذف</span>
                                             </button>
                                        </form>
                                        {{--<form method="POST" action="{{ route('delegates.destroy', $delegate->id) }}">--}}
                                            {{--@csrf--}}
                                            {{--<input name="_method" type="hidden" value="DELETE">--}}
                                            {{--<button type="submit" class="btn btn-xs btn-danger btn-flat show_confirm" data-toggle="tooltip" title='Delete'>حذف</button>--}}
                                        {{--</form>--}}
                                    </div>
                                    </div>
                                    </td>
                                    </tr>
                                    @empty
                                    <p>لا يوجد بيانات</p>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    </div>

@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `هل أنت متأكد أنك تريد حذف هذه المندوب؟`,
                text: "إذا قمت بحذف هذا ، فسيختفي إلى الأبد.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endsection